### ISSUE TITLE
Ekli şehirlerin yönlendirmeleri çalışmıyor.

### ISSUE THREAD

**Issue by mertssmnoglu** [acikkaynak/calisma-mekanlari#13]
Ekli şehirlere tıklandığında #ŞEHİR yönlendirmesi yapıyor ama emojilerden kaynaklı olarak #-ŞEHİR yönlendirmesi yapılması gerek.

**Comment by flightlesstux** [comment]
@mertssmnoglu Mert Selam, bu konu ile ilgili PR acabilirsin. Tesekkurler 🙏🏻

**Comment by mertssmnoglu** [comment]
Açtım @flightlesstux 
VS Code builtin md editöründe emoji yönlendirmesi destekleniyor ancak url üzerinden yönlendirmeler işe yaramıyor. Şimdilik `-ŞEHİR` yönlendirmesi ile çözüme kavuştu lakin dilerseniz emojileri kaldırma kararı da alabilirsiniz. Nasıl uygun görürseniz.

**Comment by flightlesstux** [comment]
> Açtım @flightlesstux VS Code builtin md editöründe emoji yönlendirmesi destekleniyor ancak url üzerinden yönlendirmeler işe yaramıyor. Şimdilik `-ŞEHİR` yönlendirmesi ile çözüme kavuştu lakin dilerseniz emojileri kaldırma kararı da alabilirsiniz. Nasıl uygun görürseniz.

Commitini merge ettim, vaktin icin tesekkurler. Ayrica bu repository hepimizin, nasil uygun gorursek, o sekilde duzenleyebiliriz : )

**Comment by mertssmnoglu** [comment]
> > Açtım @flightlesstux VS Code builtin md editöründe emoji yönlendirmesi destekleniyor ancak url üzerinden yönlendirmeler işe yaramıyor. Şimdilik `-ŞEHİR` yönlendirmesi ile çözüme kavuştu lakin dilerseniz emojileri kaldırma kararı da alabilirsiniz. Nasıl uygun görürseniz.
> 
> Commitini merge ettim, vaktin icin tesekkurler. Ayrica bu repository hepimizin, nasil uygun gorursek, o sekilde duzenleyebiliriz : )

Teşekkürler. O zaman mesajımı topluluk nasıl uygun görürse olarak yinelemek isterim. Bununla ilgili bir anket çalışmasına girilebilir mi?

**Comment by flightlesstux** [comment]
> > > Açtım @flightlesstux VS Code builtin md editöründe emoji yönlendirmesi destekleniyor ancak url üzerinden yönlendirmeler işe yaramıyor. Şimdilik `-ŞEHİR` yönlendirmesi ile çözüme kavuştu lakin dilerseniz emojileri kaldırma kararı da alabilirsiniz. Nasıl uygun görürseniz.
> > 
> > 
> > Commitini merge ettim, vaktin icin tesekkurler. Ayrica bu repository hepimizin, nasil uygun gorursek, o sekilde duzenleyebiliriz : )
> 
> Teşekkürler. O zaman mesajımı topluluk nasıl uygun görürse olarak yinelemek isterim. Bununla ilgili bir anket çalışmasına girilebilir mi?

@eser burada sana ihtiyac var 🙏🏻
