### ISSUE TITLE
Web sitesi

### ISSUE THREAD

**Issue by code-a-man** [acikkaynak/calisma-mekanlari#34]
Next.js ve PWA kullanarak kendimce bir web sitesi oluşturdum. Bu repodan README.md dosyasını çekip işleyip sitede gösteriyor. Bazı sütunlar eksik olabildiğinden dolayı bazı şehirlerde hata mevcut.

Link: https://calisma-mekanlari-app.vercel.app
Repo: https://github.com/code-a-man/calisma-mekanlari-app

**Comment by flightlesstux** [comment]
@code-a-man eline saglik, cok guzel gozukuyor! : ) eksik olan sutunlar icin, repo'ya commit atabilirsin aslinda. sutunlarin iclerini doldurman sart degil, "N/A" yazip gecebilirsin.

**Comment by code-a-man** [comment]
Teşekkür ederim abi sevindim. Hemen ilgili düzenlemeleri yapacağım 🫡

**Comment by flightlesstux** [comment]
@code-a-man dilersen, vercel kismini da bu repoya gonder. ayri ayri durmasin : )

**Comment by code-a-man** [comment]
Forklamadan projeye nasıl dahil edeceğimi bilmiyorum. Nasıl çözeceğimi araştırdım fakat senaryoya uygun bir şey bulamadım. Ayrı bir branchte mi site olacak yoksa main branchinde klasörün altında mı olması gerekiyor /docs mantığı gibi?

**Comment by flightlesstux** [comment]
senin https://github.com/code-a-man/calisma-mekanlari-app reponun icerigini, `calisma-mekanlari` reposunun icinde `/web-ui` diye bi klasor yapabiliriz. istersen, CI/CD yapilandirmasi da yapariz bizim repo icerisinde, o klasore commit geldiginde deployment olur vs.

**Comment by code-a-man** [comment]
feat/web-ui branchine pull request açtım.
CI/CD konusunda vercele bağlarsak güzel olur gerçekten abi. Yeni bir deploy oluşturup urlyi de kısaltabiliriz calisma-alanlari.vercel.app şeklinde. 
Ayrıyeten şu anki haliyle siteye girildiğinde client tarafında bilgileri github linkiyle readme dosyasından çekiyor. Onun yerine deploy olurken actions ile json dosyası oluşturursak clientın tabloyu çekmesine gerek kalmadan çalışabilir veya actions yerine direkt next.js kendi içinde de build alırken yapabiliyordur bilmiyorum araştıracağım abi.

**Comment by ramazansancar** [comment]
Bu tamamlandığı için closed konumuna çekebilir miyiz? Teşekkürler @flightlesstux

**Comment by ramazansancar** [comment]
@code-a-man Projede şu an bir sıkıntı var. Şehir listesi çekilemiyor.

**Comment by code-a-man** [comment]
> @code-a-man Projede şu an bir sıkıntı var. Şehir listesi çekilemiyor.

Bilgilendirme için teşekkürler #58 de sorunu çözdüm bir tablo doğru girilmemişti.

**Comment by ramazansancar** [comment]
> > @code-a-man Projede şu an bir sıkıntı var. Şehir listesi çekilemiyor.
> 
> Bilgilendirme için teşekkürler #58 de sorunu çözdüm bir tablo doğru girilmemişti.

Bu stilin doğru olması için prettier ile bir şey yapılabilir mi? MD için hiç kullanmadım.

**Comment by code-a-man** [comment]
@ramazansancar ben vscode eklentisini kullanıyorum
https://github.com/DavidAnson/markdownlint
pull requestte kontrol etmesi veya düzeltmesi için de GitHub Actions olanı var sanırım. Çok bilgim yok sadece sağ tıklayıp format document diyip geçiyorum ben.
