### ISSUE TITLE
Info message for each city

### ISSUE THREAD

**Issue by 4Furki4** [acikkaynak/calisma-mekanlari#9]
Should we include a message similar to this message for each city ? 

> 🎯 Bu reponun amacı, herkesin İzmir'de bildiği çalışma mekanlarını bir araya getirmek.
> ➕ Eklemek istediğiniz mekanı README.md içinde yazınız.
> 🔄 Sonra GitHub'a dev branchından pushlayıp master a merge request açınız.

I think having a message as the same as the develop branch makes more sense.

**Comment by snturk** [comment]
Instead, we can add a "Notes" column for each row like this PR -> #7

**Comment by flightlesstux** [comment]
The notes column is enough for everybody : )
